server:
    port: 8080
    servlet:
        context-path: /corefw

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/testdb
        username: root
        password: root
    jpa:
        hibernate:
             ddl-auto: validate
        properties:
             hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    liquibase:
        change-log: classpath:changelog/master.xml
